apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: curl
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: curl
    spec:
      containers:
      - image: docker.io/tutum/curl
        imagePullPolicy: IfNotPresent
        name: curl
        command: [ "sleep" ]
        args:
        - 1000h
