apiVersion: v1
kind: Service
metadata:
  name: deathstar
  labels:
    app: deathstar
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: deathstar
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deathstar
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: deathstar
        version: v1
    spec:
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: deathstar
